server:
  port: 8084

spring:
  application:
    name: api-gateway
#  cloud:
#    discovery:
#      locator:
#        enabled: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#          filters:
#            - RemoveRequestHeader=Cookie
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/products/**
#          filters:
#            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/