server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak_db
    username: keycloak
    password: keycloak_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/master"
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:8080/realms/master"
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: jsexlfuzkclYQmIxPjKYg7etCPBcjuO8
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"

realm: master
server-url: "http://localhost:8080"
name: admin
password: admin