CREATE TABLE IF NOT EXISTS products (
    idProduct SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAM NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAM NOT NULL,
    tag VARCHAR(50) NOT NULL,
    price DECIMAL NOT NULL
);