CREATE TABLE products (
    idProduct SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAM NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAM NOT NULL,
    description VARCHAR(1000) NOT NULL,
    price DECIMAL NOT NULL,
    count INT NOT NULL
);