version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: users
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db:5432
      DB_DATABASE: users
      DB_USER: myuser
      DB_PASSWORD: sa
      KEYCLOAK_HOSTNAME: localhost
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: start-dev